### PR TITLE
[WIP] v2.0.0

### PR DESCRIPTION
**Pull request by fukamachi**
I started a new experimental project named [Lack](https://github.com/fukamachi/lack). It was written from scratch with performance and simplicity in mind. 

It aims to be a gut of the next major release of Clack. Major changes are:

* No classes for component and middleware.
  * Component and middleware are just a function.
* Better 'builder' (Lack.Builder)
  * Allow short keywords for a middleware name.
* Separate many packages into individual systems (even core packages).
* Make request & response object smaller

Other parts should be compatible to Clack's. Handlers & Middlewares should be able to be used in the new spec.

I've not decided to keep Lack being an individual project yet.

All comments are welcomed.

### CODE REVIEW

**Comment by fukamachi** [comment]
I decided to make Lack be separated from Clack. It is an application builder of Clack v1 and Clack v2 is only an abstraction layer of HTTP.

Many packages including bundled middlewares are going to be deleted and to be replaced by Lack's. It would break existing Clack applications, though.
For easy migrating to Clack v2, I added "clack-v1-compat" system. Existing Clack application can be migrated just by replacing `:clack` by `:clack-v1-compat` in `:depends-on` list.

**Comment by fukamachi** [comment]
Okay, v2 is going to be released in the next Quicklisp release.

**Comment by jonatack** [comment]
Nice! :tada:

**Comment by eudoxia0** [comment]
oh boy #excitement

**Comment by Rudolph-Miller** [comment]
:tada:

**Pull request merged**
